---
- name: Add Zoneminder PPA
  apt_repository:
    repo: "ppa:iconnor/zoneminder-1.36"

- name: Install Zoneminder
  apt:
    update_cache: yes
    state: present
    name: "zoneminder={{ zm_version | default('1.36.33-jammy1', true) }}"

- name: Enable Apache modules
  apache2_module:
    state: present
    name:
      - rewrite

- name: Create symbolic link apache 
  file:
    src: /etc/apache2/conf-avalible/zoneminder.conf
    dest: /etc/apache2/conf-enabled/zoneminder.conf 
    state: link
  notify: restart apache

- name: Start Zoneminder service
  service:
    name: zoneminder
    state: started
    enabled: yes

